import type { IndicatorCategory, PrismaClient } from "@prisma/client";

type IndicatorSeed = {
  slug: string;
  name: string;
  shortName: string;
  category: IndicatorCategory;
  unit: string;
  precision?: number;
  higherIsBetter?: boolean | null;
  description: string;
  methodology: string;
  periodicity: string;
  municipalLevel?: boolean;
  displayOrder: number;
};

/**
 * Definições de indicadores. `municipalLevel: false` marca séries que só
 * existem em recorte estadual ou nacional — nesses casos a interface diz
 * "não há série municipal disponível" em vez de exibir um número inventado.
 */
export const INDICATORS: IndicatorSeed[] = [
  {
    slug: "populacao",
    name: "População residente estimada",
    shortName: "População",
    category: "DEMOGRAFIA",
    unit: "pessoas",
    higherIsBetter: null,
    description: "População residente estimada para o município no ano de referência.",
    methodology: "IBGE — Estimativas da População (SIDRA, tabela 6579).",
    periodicity: "ANUAL",
    displayOrder: 10,
  },
  {
    slug: "densidade-demografica",
    name: "Densidade demográfica",
    shortName: "Densidade",
    category: "DEMOGRAFIA",
    unit: "hab/km2",
    precision: 1,
    higherIsBetter: null,
    description: "População residente dividida pela área territorial do município.",
    methodology:
      "Derivado: população estimada (IBGE) ÷ área territorial calculada a partir da malha municipal do IBGE.",
    periodicity: "ANUAL",
    displayOrder: 20,
  },
  {
    slug: "area-territorial",
    name: "Área territorial",
    shortName: "Área",
    category: "DEMOGRAFIA",
    unit: "km2",
    precision: 1,
    higherIsBetter: null,
    description: "Extensão territorial do município.",
    methodology:
      "Calculada pelo Atlas SP por geometria esférica sobre a malha municipal do IBGE. Divergência típica inferior a 1% em relação à área oficial publicada.",
    periodicity: "IRREGULAR",
    displayOrder: 30,
  },
  {
    slug: "pib",
    name: "Produto Interno Bruto",
    shortName: "PIB",
    category: "ECONOMIA",
    unit: "BRL",
    higherIsBetter: true,
    description: "PIB municipal a preços correntes.",
    methodology: "IBGE — PIB dos Municípios (SIDRA, tabela 5938).",
    periodicity: "ANUAL",
    displayOrder: 40,
  },
  {
    slug: "pib-per-capita",
    name: "PIB per capita",
    shortName: "PIB per capita",
    category: "ECONOMIA",
    unit: "BRL_UNIT",
    precision: 0,
    higherIsBetter: true,
    description: "PIB municipal dividido pela população residente estimada.",
    methodology: "IBGE — PIB dos Municípios, razão publicada pela própria fonte.",
    periodicity: "ANUAL",
    displayOrder: 50,
  },
  {
    slug: "vab-industria",
    name: "Valor adicionado bruto — indústria",
    shortName: "VAB indústria",
    category: "ECONOMIA",
    unit: "BRL",
    higherIsBetter: null,
    description: "Valor adicionado bruto da indústria a preços correntes.",
    methodology: "IBGE — PIB dos Municípios, por atividade econômica.",
    periodicity: "ANUAL",
    displayOrder: 60,
  },
  {
    slug: "vab-servicos",
    name: "Valor adicionado bruto — serviços",
    shortName: "VAB serviços",
    category: "ECONOMIA",
    unit: "BRL",
    higherIsBetter: null,
    description:
      "Valor adicionado bruto dos serviços, exclusive administração, defesa, educação e saúde públicas.",
    methodology: "IBGE — PIB dos Municípios, por atividade econômica.",
    periodicity: "ANUAL",
    displayOrder: 70,
  },
  {
    slug: "vab-agropecuaria",
    name: "Valor adicionado bruto — agropecuária",
    shortName: "VAB agropecuária",
    category: "ECONOMIA",
    unit: "BRL",
    higherIsBetter: null,
    description: "Valor adicionado bruto da agropecuária a preços correntes.",
    methodology: "IBGE — PIB dos Municípios, por atividade econômica.",
    periodicity: "ANUAL",
    displayOrder: 80,
  },
  {
    slug: "vab-administracao",
    name: "Valor adicionado bruto — administração pública",
    shortName: "VAB administração",
    category: "ECONOMIA",
    unit: "BRL",
    higherIsBetter: null,
    description:
      "Valor adicionado bruto da administração, defesa, educação e saúde públicas e seguridade social.",
    methodology: "IBGE — PIB dos Municípios, por atividade econômica.",
    periodicity: "ANUAL",
    displayOrder: 90,
  },
  {
    slug: "emprego-formal",
    name: "Estoque de empregos formais",
    shortName: "Empregos formais",
    category: "TRABALHO",
    unit: "vinculos",
    higherIsBetter: true,
    description: "Vínculos celetistas ativos em 31 de dezembro do ano de referência.",
    methodology: "MTE — RAIS, agregada por município.",
    periodicity: "ANUAL",
    displayOrder: 100,
  },
  {
    slug: "saldo-empregos",
    name: "Saldo de empregos formais",
    shortName: "Saldo de empregos",
    category: "TRABALHO",
    unit: "vinculos",
    higherIsBetter: true,
    description: "Admissões menos desligamentos no período de referência.",
    methodology: "MTE — Novo CAGED, agregado por município.",
    periodicity: "MENSAL",
    displayOrder: 110,
  },
  {
    slug: "salario-medio",
    name: "Salário médio do emprego formal",
    shortName: "Salário médio",
    category: "RENDA",
    unit: "BRL_UNIT",
    higherIsBetter: true,
    description: "Remuneração média mensal dos vínculos formais ativos.",
    methodology: "MTE — RAIS. Valores nominais, sem deflacionamento.",
    periodicity: "ANUAL",
    displayOrder: 120,
  },
  {
    slug: "empresas-ativas",
    name: "Empresas ativas",
    shortName: "Empresas",
    category: "EMPRESAS",
    unit: "empresas",
    higherIsBetter: null,
    description: "Estabelecimentos com CNPJ ativo sediados no município.",
    methodology: "Receita Federal — base pública de CNPJ.",
    periodicity: "MENSAL",
    displayOrder: 130,
  },
  {
    slug: "abertura-empresas",
    name: "Abertura líquida de empresas",
    shortName: "Abertura de empresas",
    category: "EMPRESAS",
    unit: "empresas",
    higherIsBetter: true,
    description: "Aberturas menos baixas de CNPJ no período.",
    methodology: "Receita Federal — base pública de CNPJ, situação cadastral por data.",
    periodicity: "MENSAL",
    displayOrder: 140,
  },
  {
    slug: "receita-municipal",
    name: "Receita corrente realizada",
    shortName: "Receita",
    category: "FINANCAS_PUBLICAS",
    unit: "BRL",
    higherIsBetter: null,
    description: "Receita corrente arrecadada pelo município no exercício.",
    methodology: "Tesouro Nacional — SICONFI, Declaração de Contas Anuais.",
    periodicity: "ANUAL",
    displayOrder: 150,
  },
  {
    slug: "despesa-municipal",
    name: "Despesa executada",
    shortName: "Despesa",
    category: "FINANCAS_PUBLICAS",
    unit: "BRL",
    higherIsBetter: null,
    description: "Despesa total executada pelo município no exercício.",
    methodology: "Tesouro Nacional — SICONFI, Declaração de Contas Anuais.",
    periodicity: "ANUAL",
    displayOrder: 160,
  },
  {
    slug: "investimento-publico",
    name: "Investimento público municipal",
    shortName: "Investimento público",
    category: "FINANCAS_PUBLICAS",
    unit: "BRL",
    higherIsBetter: true,
    description: "Despesas classificadas como investimento no exercício.",
    methodology: "Tesouro Nacional — SICONFI, grupo de natureza da despesa 4.",
    periodicity: "ANUAL",
    displayOrder: 170,
  },
  {
    slug: "exportacoes",
    name: "Exportações",
    shortName: "Exportações",
    category: "COMERCIO_EXTERIOR",
    unit: "USD",
    higherIsBetter: true,
    description: "Valor exportado pelo município no período, em dólares FOB.",
    methodology: "MDIC — Comex Stat, por município de origem da mercadoria.",
    periodicity: "MENSAL",
    displayOrder: 180,
  },
  {
    slug: "idhm",
    name: "Índice de Desenvolvimento Humano Municipal",
    shortName: "IDHM",
    category: "EDUCACAO",
    unit: "indice",
    precision: 3,
    higherIsBetter: true,
    description: "Índice sintético de longevidade, educação e renda.",
    methodology: "PNUD, Ipea e Fundação João Pinheiro — Atlas do Desenvolvimento Humano.",
    periodicity: "DECENAL",
    displayOrder: 190,
  },
  {
    slug: "matriculas-educacao-basica",
    name: "Matrículas na educação básica",
    shortName: "Matrículas",
    category: "EDUCACAO",
    unit: "unidades",
    higherIsBetter: null,
    description: "Matrículas na educação básica em todas as redes.",
    methodology: "INEP — Censo Escolar.",
    periodicity: "ANUAL",
    displayOrder: 200,
  },
  {
    slug: "leitos-hospitalares",
    name: "Leitos hospitalares",
    shortName: "Leitos",
    category: "SAUDE",
    unit: "unidades",
    higherIsBetter: true,
    description: "Leitos hospitalares cadastrados no município.",
    methodology: "Ministério da Saúde — CNES.",
    periodicity: "MENSAL",
    displayOrder: 210,
  },
  {
    slug: "frota-veiculos",
    name: "Frota de veículos",
    shortName: "Frota",
    category: "INFRAESTRUTURA",
    unit: "unidades",
    higherIsBetter: null,
    description: "Frota total de veículos registrados no município.",
    methodology: "Senatran — frota por município e tipo de veículo.",
    periodicity: "MENSAL",
    displayOrder: 220,
  },
  {
    slug: "taxa-desocupacao",
    name: "Taxa de desocupação",
    shortName: "Desocupação",
    category: "TRABALHO",
    unit: "%",
    precision: 1,
    higherIsBetter: false,
    description:
      "Percentual da força de trabalho desocupada. Não há apuração para o recorte municipal.",
    methodology:
      "IBGE — PNAD Contínua. A amostra permite divulgação apenas para o total do estado e regiões metropolitanas; o Atlas SP exibe o recorte estadual como contexto, identificado como tal.",
    periodicity: "TRIMESTRAL",
    municipalLevel: false,
    displayOrder: 230,
  },
  {
    slug: "ipca",
    name: "IPCA",
    shortName: "IPCA",
    category: "PRECOS",
    unit: "%",
    precision: 2,
    higherIsBetter: false,
    description: "Variação mensal do Índice Nacional de Preços ao Consumidor Amplo.",
    methodology:
      "IBGE — IPCA. Apurado em regiões metropolitanas selecionadas; não existe série municipal.",
    periodicity: "MENSAL",
    municipalLevel: false,
    displayOrder: 240,
  },
  {
    slug: "preco-gasolina",
    name: "Preço médio da gasolina comum",
    shortName: "Gasolina",
    category: "PRECOS",
    unit: "BRL_UNIT",
    precision: 2,
    higherIsBetter: false,
    description: "Preço médio ao consumidor da gasolina comum.",
    methodology:
      "ANP — Levantamento de Preços. Apenas municípios da amostra têm série própria; os demais recebem a média estadual, sempre identificada.",
    periodicity: "SEMANAL",
    municipalLevel: false,
    displayOrder: 250,
  },
];

export async function seedIndicators(prisma: PrismaClient) {
  for (const indicator of INDICATORS) {
    const payload = {
      name: indicator.name,
      shortName: indicator.shortName,
      category: indicator.category,
      unit: indicator.unit,
      precision: indicator.precision ?? 0,
      higherIsBetter: indicator.higherIsBetter ?? null,
      description: indicator.description,
      methodology: indicator.methodology,
      periodicity: indicator.periodicity,
      municipalLevel: indicator.municipalLevel ?? true,
      displayOrder: indicator.displayOrder,
    };
    await prisma.indicator.upsert({
      where: { slug: indicator.slug },
      update: payload,
      create: { slug: indicator.slug, ...payload },
    });
  }
  return prisma.indicator.count();
}
